Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace workshop_asp.Models
{
    [Table("orders")]
    public class Order
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public string OrderId { get; set; }
        public string UserId { get; set; }
        public ApplicationUser user { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Province { get; set; }

        [StringLength(5)]
        public string PostalCode { get; set; }

        [StringLength(10)]
        public string Phone { get; set; }
        public decimal Total { get; set; }
        public string OrderStatus { get; set; }
        public DateTime OrderDate { get; set; }
    }
}

Controllers/OrderDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using workshop_asp.Data;
using workshop_asp.Utils;

namespace workshop_asp.Controllers
{
    public class OrderDetailsController : Controller
    {
        AppDb db = new AppDb();
        private CartFunc cart = new CartFunc();

        public OrderDetailsController()
        {
            ViewBag.CountCart = cart.CountItemCart();
        }

        // GET: OrderDetails
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult OrderDetailPrview(string id)
        {
            ViewBag.Order_Status = db.Orders.Find(id).OrderStatus;
            var orderDetails = db.OrderDetails.Include(it => it.product).ToList()
                .Where(it => it.OrderId == id)
                .Select(it => it).ToList();
            return View(orderDetails);
        }
    }
}

Controllers/OrdersController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using workshop_asp.Data;
using workshop_asp.Models;
using workshop_asp.Utils;

namespace workshop_asp.Controllers
{
    public class OrdersController : Controller
    {
        AppDb db = new AppDb();
        public CartFunc cart = new CartFunc();
        public List<OrderDetail> OrderDetail = new List<OrderDetail>();
        public Order Order = new Order();
        public Product Product = new Product();

        public OrdersController()
        {
            ViewBag.CountCart = cart.CountItemCart();
        }

        // GET: Order
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult OrderHistory()
        {
            var orders = db.Orders.ToList()
                .Where(it => it.UserId == User.Identity.GetUserId())
                .Select(it => it).ToList();
            return View(orders);
        }

        public ActionResult ShoppingCart()
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            return View(cart.GetCartDetail());
        }

        [HttpPost]
        public ActionResult ShoppingCart(CartDetail cartDetail)
        {
            var id = Guid.NewGuid().ToString();
            var prosucts = db.Products.ToList();
            if (cart.GetCartDetail().Any())
            {
                Order.OrderId = id;
                Order.FirstName = cartDetail.FirstName;
                Order.LastName = cartDetail.LastName;
                Order.Address = cartDetail.Address;
                Order.City = cartDetail.City;
                Order.Country = cartDetail.Country;
                Order.Province = cartDetail.Province;
                Order.PostalCode = cartDetail.PostalCode;
                Order.Phone = cartDetail.Phone;
                Order.OrderDate = DateTime.Now;
                Order.OrderStatus = "Pendding";
                Order.Total = cart.GetCartDetail().Sum(it => it.SubTotal);
                Order.UserId = User.Identity.GetUserId();

                db.Orders.Add(Order);

                foreach (var item in cart.GetCartDetail())
                {
                    OrderDetail.Add(new OrderDetail
                    {
                        OrderId = id,
                        ProductId = item.ProductId,
                        Quantity = item.Quantity,
                        UnitPrice = item.UnitPrice,
                        SubTotal = item.SubTotal,
                    });

                    var ent = db.Set<Product>().Find(item.ProductId.Value);
                    ent.UnitsInStock = prosucts.FirstOrDefault(it => it.ProductId == item.ProductId).UnitsInStock - item.Quantity;
                    ent.UnitsOnOrder = prosucts.FirstOrDefault(it => it.ProductId == item.ProductId).UnitsInStock + item.Quantity;
                    db.SaveChanges();
                }

                db.OrderDetails.AddRange(OrderDetail);
                db.SaveChanges();
                cart.ClearCart();
                ViewBag.CountCart = cart.CountItemCart();
                var orders = db.Orders.ToList()
                     .Where(it => it.UserId == User.Identity.GetUserId())
                     .Select(it => it).ToList();

                return RedirectToAction("OrderHistory", orders);
            }
            return View(cart.GetCartDetail());
        }

        public ActionResult OrderView()
        {
            return View(db.Orders.Include(o => o.user).ToList());
        }
    }
}

Views/Orders/OrderHistory.cshtml
@model IEnumerable<workshop_asp.Models.Order>
@{
    ViewBag.Title = "OrderHistory";
    var row = 0;
}
<style>
    .text-norder {
        font-size: 28px;
        margin-top: 100px;
    }
</style>

<div class="container">
    <h2>Order History</h2>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>#No.</th>
                <th>Order Id</th>
                <th>Order Date</th>
                <th>Total</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var order in Model)
            {
                <tr>
                    <td>@(++row)</td>
                    <td>@order.OrderId</td>
                    <td>@order.OrderDate</td>
                    <td>@order.Total</td>
                    <td>@order.OrderStatus</td>
                    <td>

                        <a class="btn btn-default" href="@Url.Action("OrderDetailPrview","OrderDetails",new { id = order.OrderId })">Detail</a>
                        <button class="btn btn-success">Accept</button>
                    </td>
                </tr>
            }

        </tbody>
    </table>
    @if (!Model.Any())
    {
        <p class="text-center text-norder">You haven't placed any orders yet.</p>
    }
</div>

Views/Orders/OrderView.cshtml
@model IEnumerable<workshop_asp.Models.Order>
@{
    ViewBag.Title = "OrderView";
    var row = 0;
}
<style>
    .text-norder {
        font-size: 28px;
        margin-top: 100px;
    }
</style>

<div class="container">
    <h2>Order History</h2>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>#No.</th>
                <th>Order Id</th>
                <th>Order Date</th>
                <th>Total</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var order in Model)
            {
                <tr>
                    <td>@(++row)</td>
                    <td>@order.OrderId</td>
                    <td>@order.OrderDate</td>
                    <td>@order.Total</td>
                    <td>@order.OrderStatus</td>
                    <td>

                        <a class="btn btn-default" href="@Url.Action("OrderDetailPrview","OrderDetails",new { id = order.OrderId })">Detail</a>
                        <button class="btn btn-success">Accept</button>
                    </td>
                </tr>
            }

        </tbody>
    </table>
    @if (!Model.Any())
    {
        <p class="text-center text-norder">You haven't placed any orders yet.</p>
    }
</div>

Views/Orders/ShoppingCart.cshtml
@{
    ViewBag.Title = "ShoppingCart";
    var i = 0;
    decimal total = 0;

}
<style>
    .product-img {
        max-width: 200px;
    }

        .product-img img {
            width: 100%;
        }

    table.tb-shopcart {
        border: 1px solid #808080;
    }

    /*th {
        padding: 15px;
    }

    td.cart-detail {
        position: relative;
        padding: 15px 15px;
    }*/

    .cart-detail span {
        position: absolute;
        top: 0;
    }

    input, select, textarea {
        max-width: 500px;
    }

    .address-card {
        padding: 14px 20px;
        height: 425px;
        border: 1px solid #808080;
    }

    .address-head {
        border-bottom: 1px solid;
        margin-bottom: 20px;
    }
</style>

<div class="container">
    <h2>ShoppingCart</h2>
    <div class="row">
        <div class="col-md-6">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th class="col-md-1">#No.</th>
                            <th class="col-md-6">Product</th>
                            <th>Price</th>
                            <th>Qty</th>
                            <th>SubTotal</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            total += item.SubTotal;
                            <tr>
                                <td>
                                    @*<div class="product-img">
                                            <img src="@item.product.ImagePath" />
                                        </div>*@
                                    <span>@(++i)</span>
                                </td>
                                <td>
                                    <span>@item.product.ProductName</span>
                                </td>
                                <td>
                                    <span>@item.UnitPrice</span>
                                </td>
                                <td>
                                    <span>@item.Quantity</span>
                                </td>
                                <td>
                                    <span> @String.Format("{0:n}", @item.SubTotal)</span>
                                </td>
                            </tr>
                        }
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="4" class="text-right">
                                <strong>Total</strong>
                            </td>
                            <td>
                                <strong>@String.Format("{0:n}", @total)</strong>
                                <small>฿</small>
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>

        <div class="col-md-6">
            <div class="row col-md-12">
                <form asp-action="ShoppingCart" method="post">
                    <div class="address-card">
                        <div class="address-head">
                            <h4>Shipping address</h4>
                        </div>
                        <div class="address-body">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="text" class="form-control" name="FirstName" placeholder="First Name">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="text" class="form-control" name="LastName" placeholder="Last Name">
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <textarea type="text" class="form-control" name="Address" placeholder="Address"></textarea>
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" name="City" placeholder="City">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <input type="text" class="form-control" name="Country" placeholder="Country">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <input type="text" class="form-control" name="Province" placeholder="Province">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <input type="number" class="form-control" name="PostalCode" placeholder="Postal Code">
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <input type="number" class="form-control" name="Phone" placeholder="Phone">
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-default btn-block">Check Out</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-md-12">

            </div>
        </div>
    </div>
</div>